version: '0.1'

services:
  app:
    image: 'city-bike-app:latest'
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    container_name: city-bike-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - src/main/docker/project.env

  db:
    image: 'docker.io/postgres:13.1-alpine'
    container_name: city-bike-db
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - src/main/docker/project.env
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume: