version: '0.1'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: city-bike-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - project.env

  db:
    image: 'postgres:13.1-alpine'
    container_name: city-bike-db
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - project.env
    volumes:
      - ./data:/var/lib/postgresql/data